name: code_world
description: A new Flutter project.

publish_to: 'none'

version: 4.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  animations: ^2.0.11
  app_settings: ^5.1.1
  cloud_firestore: ^4.17.4
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  date_format: ^2.0.7
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.1.0
  image_picker: ^1.1.1
  internet_connection_checker_plus: ^2.3.0
  introduction_screen: ^3.1.14
  lint: ^2.3.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pixel_perfect: ^1.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  webview_flutter: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/profileImg.jpg
    - assets/code.png
    - assets/favourite.png
    - assets/read.png
    - assets/ui.png
    - assets/education.png
    - assets/search.png
    - assets/love.png
    - assets/logout.png
    - assets/profile1.png
    - assets/coding.png
    - assets/info.png
    - assets/star.png
    - assets/question.png