name: code_world
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_storage: ^8.0.3
  firebase_core: ^1.0.2
  toast: ^0.1.5
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.5
  splashscreen: ^1.3.5
  uuid: ^3.0.4
  provider: ^5.0.0
  date_format: ^2.0.2
  shared_preferences: ^2.0.5
  image_picker: ^0.7.4
  permission_handler: ^7.1.0
  path_provider: ^2.0.1
  connectivity: ^3.0.3
  loading: ^1.0.2
  shimmer: ^2.0.0
  animations: ^2.0.0
  google_fonts: ^2.0.0
  lint: ^1.5.3
  after_layout: ^1.1.0
  pixel_perfect: ^1.1.0
  flutter_spinkit: ^5.0.0
  app_settings: ^4.1.0
  introduction_screen: ^1.0.9
  webview_flutter: ^0.3.20+2
  font_awesome_flutter: ^8.2.0
  url_launcher: ^6.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/profileImg.jpg
    - assets/code.png
    - assets/favourite.png
    - assets/read.png
    - assets/ui.png
    - assets/education.png
    - assets/search.png
    - assets/love.png
    - assets/logout.png
    - assets/profile1.png
    - assets/coding.png
    - assets/info.png
    - assets/star.png
    - assets/question.png